version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_SCHEMA}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5431:80'
    depends_on:
      - postgres

  mysql:
    container_name: mysql
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'

  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - "8001:80"