version: '2'
services:

  mysql:
    container_name: mysql
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3305:3306'

  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - "8001:80"